export const UPDATE_BOOKS = "UPDATE_BOOKS";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const UPDATE_CURRENT_SEARCH = "UPDATE_CURRENT_SEARCH";
export const UPDATE_READ_BOOKS = "UPDATE_READ_BOOKS";
export const ALL_BOOKS = "ALL_BOOKS"
